[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
raffle = "RAFFLv4sQoBPqLLqQvSHLRSFNnnoNekAbXfSegbQygF"

[programs.devnet]
raffle = "RAFFLv4sQoBPqLLqQvSHLRSFNnnoNekAbXfSegbQygF"

[programs.mainnet]
raffle = "RAFFLv4sQoBPqLLqQvSHLRSFNnnoNekAbXfSegbQygF"

[registry]
url = "https://api.apr.dev"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
# Token Metadata program
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
# Token Auth Rules program
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
[[test.validator.clone]]
# Metaplex ruleSet
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"
# Solana Randomness Service
[[test.validator.clone]]
address = "RANDMo5gFnqnXJW5Z52KNmd24sAo95KAd5VbiCtq5Rh"

# Sbv3 Program ID
[[test.validator.clone]]
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

# Sbv3 ProgramStateAccount
[[test.validator.clone]]
address = "5MFs7RGTjLi1wtKNBFRtuLipCkkjs4YQwRRU9sjnbQbS"

# Sbv3 IDL
[[test.validator.clone]]
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[test]
upgradeable = true

[provider]
# cluster = "Localnet"
# wallet = "/Users/joefitter/.config/solana/id.json"
# cluster = "Devnet"
# wallet = "/Users/joefitter/.config/solana/launchpad-wallets/xlaunchpad.json"
# cluster = "https://rpc.helius.xyz/?api-key=d8bb99b6-342b-40d8-9d9f-731827589922"
cluster = "Mainnet"
wallet = "/Users/joefitter/.config/solana/launchpad-wallets/xlaunchpad.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
